= arithmetics-go
:author: Pedro Lamarão <pedro.lamarao@purpura.dev.br>
:icons: font

In link:README.adoc[english].

A biblioteca `arithmetics-go` contém rotinas para aritmética com inteiros não-negativos "longos".

Este é um projeto educacional com o propósito de aprendizado e compartilhamento de matemática algorítmica.

Para executar os testes de corretude:

[source,shell]
----
go test ./arithmetics -rapid.checks=1_000
----

NOTE: A opção `-rapid.checks` define a quantidade de amostras aleatórias verificadas por cada teste.

Para executar os testes de desempenho:

[source,shell]
----
go test ./arithmetics -bench .
----

Isso deve testar esta biblioca contra a biblioteca padrão.

NOTE: Você deve usar Go 1.26+ para resultados realistas; veja as notas sobre `B.Loop` em link:https://go.dev/doc/go1.26#testingpkgtesting[]

== Referências

* Donald E. Knuth, "The Art of Computer Programming", volume 2, "Seminumerical Algorithms", third edition, ISBN 0-201-89684-2

* MMIXmasters, "MIX to MMIX Conversion", https://mmix.cs.hm.edu/mmixmasters/index.html#MIXtoMMIX

* Peter Montgomery, Torbjörn Granlund, "Division by Invariant Integers using Multiplication", PLDI '94, DOI: 10.1145/178243.178249

* Alexander Stepanov, Paul McJones, "Elements of Programming", Addison-Wesley, 2009, ISBN 978-0-321-63537-2

* Niels Möller, Torbjörn Granlund, "Improved division by invariant integers", IEEE Transactions on Computers, Volume 60, Issue 2, February 2011, DOI: 10.1109/TC.2010.143

* Alexander Stepanov, Daniel Rose, "From Mathematics to Generic Programming", Addison Wesley, 2015, ISBN 978-0-321-94204-3